version: '3.6'

services:
  db:
    container_name: mvpmatch-db
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mvpmatch
      - POSTGRES_USER=mvpmatch
      - POSTGRES_PASSWORD=Aehie4aeLeiz
    volumes:
      # scripts
      - ./postgres-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mvpmatch-dbdata:/var/lib/postgresql/data

  db_test:
    container_name: mvpmatch-db-test
    image: postgres:15.1
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=mvpmatch_test
      - POSTGRES_USER=mvpmatch_test
      - POSTGRES_PASSWORD=mvpmatch_test

  back:
    container_name: mvpmatch-back
    build: ../back
    ports:
      - 3000:3000
    environment:
      - DB_NAME=mvpmatch
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=mvpmatch
      - DB_PASSWORD=Aehie4aeLeiz
      - PORT=3000
      - JWT_SECRET=ohNe1Niemaitheopoo7uk1Woh8Che7Ko
    depends_on:
      - db

volumes:
  mvpmatch-dbdata:
    name: mvpmatch-dbdata